repository:
  name: pdf-img-converter
  description: A simple cli to convert pdf to images and back.
  homepage: https://github.com/cdubos-fr/pdf-img-converter
  topics: github, probot
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - name: bug
    color: CC0000
    description: An issue with the system 🐛.

  - name: feature
    color: '#336699'
    description: New functionality.

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        checks: [
          "Bump version, create changelog and release",
        ]
      enforce_admins: true
      required_linear_history: true
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions:
        users: []
        teams: []
      allow_deletions: false
      allow_force_pushes: false
