name: CD -> Bump version and create release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bump-version:
    if: endsWith(github.event.head_commit.message, '[tag]') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: "Bump version, create changelog and release"
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@0.21.0
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          changelog_increment_filename: body.md
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: "body.md"
          tag_name: "${{ env.REVISION }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
